---
# first task: compile and install FFMPEG and its dependencies
- hosts: all
  tasks:
    - name: install ffmpeg build dependencies
      apt: name={{ item }}
      with_items:
          - git
          - mercurial
          - build-essential
          - autoconf
          - automake
          - cmake
          - pkg-config
          - texinfo
          - yasm
          - libass-dev
          - libfreetype6-dev
          - libsdl1.2-dev
          - libtheora-dev
          - libtool
          - libva-dev
          - libvdpau-dev
          - libvorbis-dev
          - libxcb1-dev
          - libxcb-shm0-dev
          - libxcb-xfixes0-dev
          - zlib1g-dev
          - libopus-dev
          - libmp3lame-dev
          - libx264-dev
          - libssl-dev
          - libxml2
          - libxml2-dev
          - libxslt1.1
          - libxslt-dev
          - libgd3
          - libgd-dev
          - libgeoip1
          - libgeoip-dev
    # dependent libraries
    # libx265
    - name: clone libx265
      command: hg clone https://bitbucket.org/multicoreware/x265 /usr/src/x265
      args:
          creates: /usr/src/x265
    - name: update libx265
      command: hg pull -u
      args:
          chdir: /usr/src/x265
    - name: configure libx265
      command: cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLED_SHARED:bool=off ../../source
      args:
          chdir: /usr/src/x265/build/linux
          creates: /usr/src/x265/build/linux/Makefile
    - name: compile libx265
      command: make -j2
      args:
          chdir: /usr/src/x265/build/linux
          creates: /usr/src/x265/build/linux/x265
    - name: install libx265
      command: make install
      args:
          chdir: /usr/src/x265/build/linux
          creates: /usr/local/bin/x265
    # libfdk-aac
    - name: clone libfdk-aac
      command: git clone https://github.com/mstorsjo/fdk-aac.git /usr/src/libfdk-aac
      args:
          creates: /usr/src/libfdk-aac
    - name: update libfdk-aac
      command: git pull origin master
      args:
          chdir: /usr/src/libfdk-aac
    - name: autoconf libfdk-aac
      command: autoreconf -fiv
      args:
          chdir: /usr/src/libfdk-aac
          creates: /usr/src/libfdk-aac/configure
    - name: configure libfdk-aac
      command: /usr/src/libfdk-aac/configure --prefix=/usr/local --disable-shared
      args:
          chdir: /usr/src/libfdk-aac
          creates: /usr/src/libfdk-aac/libtool
    - name: compile libfdk-aac
      command: make -j2
      args:
          chdir: /usr/src/libfdk-aac
          creates: /usr/src/libfdk-aac/libFDK/src/FDK_core.o
    - name: install libfdk-aac
      command: make install
      args:
          chdir: /usr/src/libfdk-aac
          creates: /usr/local/lib/libfdk-aac.a
    # libvpx
    - name: download libvpx
      shell: wget -O - https://storage.googleapis.com/downloads.webmproject.org/releases/webm/libvpx-1.4.0.tar.bz2 | tar xjvf -
      args:
          chdir: /usr/src
          creates: /usr/src/libvpx-1.4.0
    - name: configure libvpx
      command: ./configure --prefix=/usr/local --disable-examples --disable-unit-tests
      args:
          chdir: /usr/src/libvpx-1.4.0
          creates: /usr/src/libvpx-1.4.0/Makefile
    - name: compile libvpx
      command: make -j2
      args:
          chdir: /usr/src/libvpx-1.4.0
          creates: /usr/src/libvpx-1.4.0/libvpx.a
    - name: install libvpx
      command: make install
      args:
          chdir: /usr/src/libvpx-1.4.0
          creates: /usr/local/lib/libvpx.a
    # ffmpeg itself
    - name: download ffmpeg
      command: git clone https://github.com/ffmpeg/ffmpeg.git /usr/src/ffmpeg
      args:
          chdir: /usr/src
          creates: /usr/src/ffmpeg
    - name: update ffmpeg
      command: git pull origin master
      args:
          chdir: /usr/src/ffmpeg
    - name: configure ffmpeg
      command: /usr/src/ffmpeg/configure \
        --prefix=/usr/local \
        --pkg-config-flags='--static' \
        --bindir=/usr/local/bin \
        --enable-gpl --enable-version3 --enable-nonfree \
        --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame \
        --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx \
        --enable-libx264 --enable-libx265
      args:
          chdir: /usr/src/ffmpeg
          creates: /usr/src/ffmpeg/config.asm
    - name: compile ffmpeg
      command: make -j2
      args:
          chdir: /usr/src/ffmpeg
          creates: /usr/src/ffmpeg/ffmpeg
    - name: install ffmpeg
      command: make install
      args:
          chdir: /usr/src/ffmpeg
          creates: /usr/local/bin/ffmpeg
      notify:
          - update ldconfig
  handlers:
      - name: update ldconfig
        command: ldconfig

# second task: compile and install nginx and its dependencies
- hosts: all
  tasks:
    # nginx proper
    - name: download nginx
      get_url: url=http://nginx.org/download/nginx-1.9.6.tar.gz dest=/usr/src/nginx-1.9.6.tar.gz
    - name: download nginx signature
      get_url: url=http://nginx.org/download/nginx-1.9.6.tar.gz.asc dest=/usr/src/nginx-1.9.6.tar.gz.asc
    - name: install nginx signing keys
      command: gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys \
         A09CD539B8BB8CBE96E82BDFABD4D3B3F5806B4D \
         4C2C85E705DC730833990C38A9376139A524C53E \
         B0F4253373F8F6F510D42178520A9993A1C052F8 \
         65506C02EFC250F1B7A3D694ECF0E90B2C172083 \
         7338973069ED3F443F4D37DFA64FD5B17ADB39A8 \
         6E067260B83DCF2CA93C566F518509686C7E5E82 \
         573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
    - name: verify nginx zip
      command: gpg --verify /usr/src/nginx-1.9.6.tar.gz.asc /usr/src/nginx-1.9.6.tar.gz
    - name: extract nginx source
      command: tar xzvf /usr/src/nginx-1.9.6.tar.gz
      args:
          chdir: /usr/src
          creates: /usr/src/nginx-1.9.6/README
    # nginx media server
    - name: download and extract nginx media server module
      shell: wget -O - "https://github.com/arut/nginx-rtmp-module/archive/v1.1.7.tar.gz" | tar xzvf -
      args:
          chdir: /usr/src
          creates: /usr/src/nginx-rtmp-module-1.1.7/README.md
    # compile
    - name: configure nginx
      command: /usr/src/nginx-1.9.6/configure \
        --prefix=/etc/nginx
        --sbin-path=/usr/sbin/nginx
        --conf-path=/etc/nginx/nginx.conf
        --error-log-path=/var/log/nginx/error.log
        --http-log-path=/var/log/nginx/access.log
        --pid-path=/var/run/nginx.pid
        --lock-path=/var/run/nginx.lock
        --http-client-body-temp-path=/var/cache/nginx/client_temp
        --http-proxy-temp-path=/var/cache/nginx/proxy_temp
        --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp
        --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp
        --http-scgi-temp-path=/var/cache/nginx/scgi_temp
        --user=nginx
        --group=nginx
        --with-http_ssl_module
        --with-http_realip_module
        --with-http_addition_module
        --with-http_sub_module
        --with-http_dav_module
        --with-http_flv_module
        --with-http_mp4_module
        --with-http_gunzip_module
        --with-http_gzip_static_module
        --with-http_random_index_module
        --with-http_secure_link_module
        --with-http_stub_status_module
        --with-http_auth_request_module
        --with-mail
        --with-mail_ssl_module
        --with-file-aio
        --with-http_v2_module
        --with-ipv6
        --with-threads
        --with-stream
        --with-stream_ssl_module
      args:
          chdir: /usr/src/nginx-1.9.6
          creates: /usr/src/nginx-1.9.6/Makefile
    - name: compile nginx
      command: make -j 2
      args:
          chdir: /usr/src/nginx-1.9.6
          creates: /usr/src/nginx-1.9.6/objs/nginx
    - name: install nginx
      command: make install
      args:
          chdir: /usr/src/nginx-1.9.6
          creates: /usr/sbin/nginx
    - name: nginx configuration file
      template: /ansible/templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0644
# configuration and things
- hosts: all
  tasks:
      - name: setup hls and dash mounts
        mount: name={{ item.path }} src=tmpfs fstype=tmpfs opts=size={{ item.size }} state=mounted
        with_items:
            - { path: '/tmp/hls', size: '64m' }
            - { path: '/tmp/dash', size: '64m' }
